version: "3.4"
services:

  cosmoz.influxdb:
    image: influxdb:1.7-alpine
    #ports:
    #  - "8186:8086"
    #  - "8188:8088"
    networks:
      - backend
    hostname: "cosmoz.influxdb"
    volumes:
      # The /var/lib/influxdb dir has subdirs {data, meta, wal} all need to be persisted.
      - timeseriesdb-data:/var/lib/influxdb
      - "./influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - INFLUX_DB=cosmoz
    command: ["influxd", "-config", "/etc/influxdb/influxdb.conf"]
  
  cosmoz.mongodb:
    image: mvertes/alpine-mongo:latest
    #ports:
    #  - "27018:27017"
    #  - "28017"
    networks:
      - backend
    hostname: "cosmoz.mongodb"
    volumes:
      - documentdb-data:/data/db
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - MONGODB_RUN="/var/run/mongodb"
      - MONGODB_DATA="/var/lib/mongodb"
      - MONGODB_USER="mongodb"
      - MONGODB_IP="0.0.0.0"
      - MONGODB_OPTIONS="--journal"

  
  visualizer:
    image: chronograf:1.7-alpine
    depends_on:
      - cosmoz.influxdb
    #ports:
    #  - "8888:8888"
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    command: ["chronograf", "--influxdb-url=http://cosmoz.influxdb:8086"]

  cosmoz.application:
    image: cosmoz/app-rest
    build:
      dockerfile: ./Dockerfile
      context: .
      network: host
    hostname: "cosmoz.application"
    depends_on:
      - cosmoz.influxdb
      - cosmoz.mongodb
    ports:
      - "8098:8080"
    networks:
      - backend

networks:
  backend:
      
volumes:
  timeseriesdb-data:
    driver_opts:
      type: none
      device: "${PWD}/tsdb"
      o: bind
  documentdb-data:
    driver_opts:
      type: none
      device: "${PWD}/mgdb"
      o: bind
