version: "3.6"
# Requires docker-compose min version 1.22
# (for complex labels, and for $PWD in dockerfile:)
services:

  cosmoz.pipeline.application:
    image: docker.io/ternau/landscapes.cosmoz.pipeline:latest
    build:
      dockerfile: "${PWD}/Dockerfiles/pipeline.Dockerfile"
      context: ../../
    environment:
      - PYTHONUNBUFFERED=TRUE
